### ISSUE TITLE
error when compile 

### ISSUE THREAD

**Issue by maxwu8416** [AlejandroSilvestri/osmap#3] opened 2019-03-16 12:54 UTC
hi !
i just to everything from the introduction step by step also notice today's update and also generated the osmap.pb.cc and osmap.pb.h. when i compile orb_slam2 it shows some error like this : 

```
In file included from /home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:34:0:
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../include/Osmap.h:60:21: error: expected ‘)’ before ‘*’ token
  OsmapMapPoint(Osmap*);
                     ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../include/Osmap.h:70:21: error: expected ‘)’ before ‘*’ token
  OsmapKeyFrame(Osmap*);
                     ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc: In function ‘int main(int, char**)’:
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:5: error: ‘Osmap’ was not declared in this scope
     Osmap osmap = ORB_SLAM2::Osmap(SLAM);
     ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:5: note: suggested alternative:
In file included from /home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:34:0:
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../include/Osmap.h:167:7: note:   ‘ORB_SLAM2::Osmap’
 class Osmap{
       ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:11: error: expected ‘;’ before ‘osmap’
     Osmap osmap = ORB_SLAM2::Osmap(SLAM);
           ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:79:5: error: ‘osmap’ was not declared in this scope
     osmap.mapSave("myFirstMap"); // "myFirstMap" or "myFirstMap.yaml", same thing
     ^
make[2]: *** [CMakeFiles/Mono.dir/src/ros_mono.cc.o] Error 1
make[1]: *** [CMakeFiles/Mono.dir/all] Error 2
make: *** [all] Error 2

```
it seems like some structure problem should i change something from the code? or some bug from the source code ?

**Comment by AlejandroSilvestri** [comment] 2019-03-16 14:22
@maxwu8416 ,

Hi Max, I'm very interested in your problem.  I am using and recompiling osmap for a while with orb-slam2 without problems, but I am compiling it from IDE, so I am interested on seeing a cmake flawless compilation.

Since it is working fine for me,  I'm not able to reproduce these errors.  If you don't mind, I ask you to try this: add the following line to Osmap.h, in row 52 right after namespace ORB_SLAM2{   :

    class Osmap;

and let me know if this fix the error, so I add it to the repository.

Thank you!

**Comment by maxwu8416** [comment] 2019-03-17 01:59
thanks for your reply !
i added the code at where you told and compile again.
it seems improve the pointer error but still has the structure problem.
the error now look like this : 

```
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc: In function ‘int main(int, char**)’:
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:5: error: ‘Osmap’ was not declared in this scope
     Osmap osmap = ORB_SLAM2::Osmap::Osmap(SLAM);
     ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:5: note: suggested alternative:
In file included from /home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:34:0:
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/../../../include/Osmap.h:167:7: note:   ‘ORB_SLAM2::Osmap’
 class Osmap
       ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:64:11: error: expected ‘;’ before ‘osmap’
     Osmap osmap = ORB_SLAM2::Osmap::Osmap(SLAM);
           ^
/home/max/max_ws/src/ORB_SLAM2/Examples/ROS/ORB_SLAM2/src/ros_mono.cc:79:5: error: ‘osmap’ was not declared in this scope
     osmap.mapSave("myFirstMap"); // "myFirstMap" or "myFirstMap.yaml", same thing
```
and another small question, which IDE you used to compiled? and i'm using VS Code as editor btw.

**Comment by AlejandroSilvestri** [comment] 2019-03-17 13:04
Did you #include "Osmap.h"?  Make sure you put the right path to Osmap.h, like.

    #include "relative path from ros:mono.cc /Osmap.h"

Please paste the code or a link to it, so I can trace the error.

I'm using Eclipse on Linux.

**Comment by maxwu8416** [comment] 2019-03-17 15:07
yeah i already add in there, and here is the code in ros_mono.cc  

```
/**
* This file is part of ORB-SLAM2.
*
* Copyright (C) 2014-2016 Raúl Mur-Artal <raulmur at unizar dot es> (University of Zaragoza)
* For more information see <https://github.com/raulmur/ORB_SLAM2>
*
* ORB-SLAM2 is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* ORB-SLAM2 is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with ORB-SLAM2. If not, see <http://www.gnu.org/licenses/>.
*/

#include <iostream>
#include <algorithm>
#include <fstream>
#include <chrono>

#include <ros/ros.h>
#include <cv_bridge/cv_bridge.h>

#include <opencv2/core/core.hpp>

#include "../../../include/System.h"

//max
#include "../../../include/Osmap.h"

using namespace std;

class ImageGrabber
{
  public:
    ImageGrabber(ORB_SLAM2::System *pSLAM) : mpSLAM(pSLAM) {}

    void GrabImage(const sensor_msgs::ImageConstPtr &msg);

    ORB_SLAM2::System *mpSLAM;
};

int main(int argc, char **argv)
{
    ros::init(argc, argv, "Mono");
    ros::start();

    if (argc != 3)
    {
        cerr << endl
             << "Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings" << endl;
        ros::shutdown();
        return 1;
    }

    // Create SLAM system. It initializes all system threads and gets ready to process frames.
    ORB_SLAM2::System SLAM(argv[1], argv[2], ORB_SLAM2::System::MONOCULAR, true);
    //max, Construct the osmap object, can be right after SLAM construction.  You only need one instance to load and save as many maps you want.
    Osmap osmap = ORB_SLAM2::Osmap(SLAM);
    //
    ImageGrabber igb(&SLAM);

    ros::NodeHandle nodeHandler;
    ros::Subscriber sub = nodeHandler.subscribe("/bebop/image_raw", 1, &ImageGrabber::GrabImage, &igb);

    ros::spin();

    // Stop all threads
    SLAM.Shutdown();

    // Save camera trajectory
    SLAM.SaveKeyFrameTrajectoryTUM("KeyFrameTrajectory.txt");
    // When you already has a map to save
    osmap.mapSave("myFirstMap"); // "myFirstMap" or "myFirstMap.yaml", same thing

    ros::shutdown();

    return 0;
}

void ImageGrabber::GrabImage(const sensor_msgs::ImageConstPtr &msg)
{
    // Copy the ros image message to cv::Mat.
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
        cv_ptr = cv_bridge::toCvShare(msg);
    }
    catch (cv_bridge::Exception &e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
        return;
    }

    mpSLAM->TrackMonocular(cv_ptr->image, cv_ptr->header.stamp.toSec());
}

```

**Comment by AlejandroSilvestri** [comment] 2019-03-17 21:02
Right! It seems we need the prefix ORB_SLAM2::  in line 64 (i think), like this:

    ORB_SLAM2::Osmap osmap = ORB_SLAM2::Osmap(SLAM);

I hope you don't get tired of trying.

**Comment by maxwu8416** [comment] 2019-03-18 03:19
update the code like this !
```
/**
* This file is part of ORB-SLAM2.
*
* Copyright (C) 2014-2016 Raúl Mur-Artal <raulmur at unizar dot es> (University of Zaragoza)
* For more information see <https://github.com/raulmur/ORB_SLAM2>
*
* ORB-SLAM2 is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* ORB-SLAM2 is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with ORB-SLAM2. If not, see <http://www.gnu.org/licenses/>.
*/

#include <iostream>
#include <algorithm>
#include <fstream>
#include <chrono>

#include <ros/ros.h>
#include <cv_bridge/cv_bridge.h>

#include <opencv2/core/core.hpp>

#include "../../../include/System.h"

//max
#include "../../../include/Osmap.h"

using namespace std;

class ImageGrabber
{
  public:
    ImageGrabber(ORB_SLAM2::System *pSLAM) : mpSLAM(pSLAM) {}

    void GrabImage(const sensor_msgs::ImageConstPtr &msg);

    ORB_SLAM2::System *mpSLAM;
};

int main(int argc, char **argv)
{
    ros::init(argc, argv, "Mono");
    ros::start();

    if (argc != 3)
    {
        cerr << endl
             << "Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings" << endl;
        ros::shutdown();
        return 1;
    }

    // Create SLAM system. It initializes all system threads and gets ready to process frames.
    ORB_SLAM2::System SLAM(argv[1], argv[2], ORB_SLAM2::System::MONOCULAR, true);
    //max, Construct the osmap object, can be right after SLAM construction.  You only need one instance to load and save as many maps you want.
    ORB_SLAM2::Osmap osmap = ORB_SLAM2::Osmap(SLAM);
    //
    ImageGrabber igb(&SLAM);

    ros::NodeHandle nodeHandler;
    ros::Subscriber sub = nodeHandler.subscribe("/bebop/image_raw", 1, &ImageGrabber::GrabImage, &igb);

    ros::spin();

    // Stop all threads
    SLAM.Shutdown();

    // Save camera trajectory
    SLAM.SaveKeyFrameTrajectoryTUM("KeyFrameTrajectory.txt");
    // When you already has a map to save
    osmap.mapSave("myFirstMap"); // "myFirstMap" or "myFirstMap.yaml", same thing

    ros::shutdown();

    return 0;
}

void ImageGrabber::GrabImage(const sensor_msgs::ImageConstPtr &msg)
{
    // Copy the ros image message to cv::Mat.
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
        cv_ptr = cv_bridge::toCvShare(msg);
    }
    catch (cv_bridge::Exception &e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
        return;
    }

    mpSLAM->TrackMonocular(cv_ptr->image, cv_ptr->header.stamp.toSec());
}
```
and do compile, sadly still have some error, but it seems we're more close to succeed?
```
CMakeFiles/Mono.dir/src/ros_mono.cc.o: In function `main':
ros_mono.cc:(.text.startup+0x164): undefined reference to `ORB_SLAM2::Osmap::Osmap(ORB_SLAM2::System&)'
ros_mono.cc:(.text.startup+0x2d5): undefined reference to `ORB_SLAM2::Osmap::mapSave(std::string, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [../Mono] Error 1
make[1]: *** [CMakeFiles/Mono.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by AlejandroSilvestri** [comment] 2019-03-18 18:38
This is a linker error, may be it isn't able to open Osmap.o .
Do you want to share your cmake file?

**Comment by maxwu8416** [comment] 2019-03-18 18:41
Yeah sure! No problem  ~

```
cmake_minimum_required(VERSION 2.8)
project(ORB_SLAM2)

IF(NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE Release)
ENDIF()

MESSAGE("Build type: " ${CMAKE_BUILD_TYPE})

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -Wall  -O3 -march=native ")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall   -O3 -march=native")

# Check C++11 or C++0x support
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
   add_definitions(-DCOMPILEDWITHC11)
   message(STATUS "Using flag -std=c++11.")
elseif(COMPILER_SUPPORTS_CXX0X)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
   add_definitions(-DCOMPILEDWITHC0X)
   message(STATUS "Using flag -std=c++0x.")
else()
   message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()

LIST(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake_modules)

find_package(OpenCV 3.0 QUIET)
if(NOT OpenCV_FOUND)
   find_package(OpenCV 2.4.11 QUIET)
   if(NOT OpenCV_FOUND)
      message(FATAL_ERROR "OpenCV > 2.4.11 not found.")
   endif()
endif()

find_package(Eigen3 3.1.0 REQUIRED)
find_package(Pangolin REQUIRED)

include_directories(
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/include
${EIGEN3_INCLUDE_DIR}
${Pangolin_INCLUDE_DIRS}
)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)

add_library(${PROJECT_NAME} SHARED
src/System.cc
src/Tracking.cc
src/LocalMapping.cc
src/LoopClosing.cc
src/ORBextractor.cc
src/ORBmatcher.cc
src/FrameDrawer.cc
src/Converter.cc
src/MapPoint.cc
src/KeyFrame.cc
src/Map.cc
src/MapDrawer.cc
src/Optimizer.cc
src/PnPsolver.cc
src/Frame.cc
src/KeyFrameDatabase.cc
src/Sim3Solver.cc
src/Initializer.cc
src/Viewer.cc
##
src/osmap.pb.cc
src/Osmap.cpp
)

target_link_libraries(${PROJECT_NAME}
${OpenCV_LIBS}
${EIGEN3_LIBS}
${Pangolin_LIBRARIES}
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/Thirdparty/g2o/lib/libg2o.so
)

# Build examples

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Examples/RGB-D)

add_executable(rgbd_tum
Examples/RGB-D/rgbd_tum.cc)
target_link_libraries(rgbd_tum ${PROJECT_NAME})

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Examples/Stereo)

add_executable(stereo_kitti
Examples/Stereo/stereo_kitti.cc)
target_link_libraries(stereo_kitti ${PROJECT_NAME})

add_executable(stereo_euroc
Examples/Stereo/stereo_euroc.cc)
target_link_libraries(stereo_euroc ${PROJECT_NAME})


set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Examples/Monocular)

add_executable(mono_tum
Examples/Monocular/mono_tum.cc)
target_link_libraries(mono_tum ${PROJECT_NAME})

add_executable(mono_kitti
Examples/Monocular/mono_kitti.cc)
target_link_libraries(mono_kitti ${PROJECT_NAME})

add_executable(mono_euroc
Examples/Monocular/mono_euroc.cc)
target_link_libraries(mono_euroc ${PROJECT_NAME})

```

**Comment by AlejandroSilvestri** [comment] 2019-03-19 13:44
I'm guessing here.  Perhaps changing <> by "" in this include:

https://github.com/AlejandroSilvestri/osmap/blob/master/src/Osmap.cpp#L28

Please try removing the ## line in cmake file.

**Comment by Shashika007** [comment] 2019-03-20 10:22
@AlejandroSilvestri 
I did the changes that you suggested from here and I got the similar issue when i tried to build this with orb-slam2. 

[  2%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Osmap.cpp.o
In file included from /home/te600016/ORB_SLAM2/include/Osmap.h:36:0,
                 from /home/te600016/ORB_SLAM2/src/Osmap.cpp:28:
/home/te600016/ORB_SLAM2/include/System.h: In constructor ‘ORB_SLAM2::Osmap::Osmap(ORB_SLAM2::System&)’:
/home/te600016/ORB_SLAM2/include/System.h:137:10: error: ‘ORB_SLAM2::Map* ORB_SLAM2::System::mpMap’ is private
     Map* mpMap;
          ^
/home/te600016/ORB_SLAM2/src/Osmap.cpp:39:38: error: within this context
  map(static_cast<OsmapMap&>(*_system.mpMap)),
                                      ^
In file included from /home/te600016/ORB_SLAM2/include/Osmap.h:36:0,
                 from /home/te600016/ORB_SLAM2/src/Osmap.cpp:28:
/home/te600016/ORB_SLAM2/include/System.h:134:23: error: ‘ORB_SLAM2::KeyFrameDatabase* ORB_SLAM2::System::mpKeyFrameDatabase’ is private
     KeyFrameDatabase* mpKeyFrameDatabase;

**Comment by AlejandroSilvestri** [comment] 2019-03-20 11:12
@Shashika007 
YES!  Thank you.  Right there is the cause of these errors.

I realized I modified System.h, so it works when I tried it.  My mistake.

I'll fix it, but it may take a while.  Not big deal, but I have to take a moment to think, modify and test.

Right now, if you want to go further, you can delete lines 125 in System.h, the `private:` access specifier, so the following members will become public and osmap will be able to access them.

Meanwhile I'll add Osmap code the capability to access those members without modifying System.h

I appreciate your effort in seamless integrating osmap with orb_slam2.

**Comment by maxwu8416** [comment] 2019-03-20 12:24
@AlejandroSilvestri 
Sorry for too late to reply you !
In the fact i already change**( changing <> by "" in this include)** that before, when i was try to solved the opencv include problem which i already closed issue(https://github.com/AlejandroSilvestri/osmap/issues/2).but it seems nothing change after i did that.btw i solved the include opencv problem by fixed the code 
`#include <opencv2/core.hpp> `
to 
`#include <opencv2//core/core.hpp>`

Really expecting your update work! for now i'll try your suggestion and try it again.

**Comment by Shashika007** [comment] 2019-03-21 02:26
@AlejandroSilvestri 

That worked! but i got this protobuf linking error as follows. 

[ 44%] Building CXX object CMakeFiles/Mono.dir/src/ros_mono.cc.o
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::io::CodedInputStream::IncrementRecursionDepthAndPushLimit(int)'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::AssignDescriptorsTable*)'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback()'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
../../../../lib/libORB_SLAM2.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'

In the CMakeLists, i added the lib lprotobuf, but it did not solved. 

target_link_libraries(${PROJECT_NAME}
${OpenCV_LIBS}
${EIGEN3_LIBS}
${Pangolin_LIBRARIES}
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/Thirdparty/g2o/lib/libg2o.so
${PROTOBUF_LIBRARIES}
-lprotobuf
)

I also checked my protoc --version. it is already updated to the latest one "libprotoc 3.7.0"

thanks!

**Comment by Shashika007** [comment] 2019-03-21 02:44
@AlejandroSilvestri 
I already solved the problem by adding,
INCLUDE(FindProtobuf)
FIND_PACKAGE(Protobuf REQUIRED)

include_directories(
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/include
${EIGEN3_INCLUDE_DIR}
${Pangolin_INCLUDE_DIRS}
${CMAKE_CURRENT_BINARY_DIR}
${PROTOBUF_INCLUDE_DIR}
)

target_link_libraries(${PROJECT_NAME}
${OpenCV_LIBS}
${EIGEN3_LIBS}
${Pangolin_LIBRARIES}
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/Thirdparty/g2o/lib/libg2o.so
${PROTOBUF_LIBRARIES}
-lprotobuf
)

cheers !

shashika

**Comment by Shashika007** [comment] 2019-03-21 03:06
@AlejandroSilvestri 
I got this protoc mismatch error. hopefully i can find the solution for this.

/usr/bin/ld: warning: libprotobuf.so.9, needed by ../../../../lib/libORB_SLAM2.so, may conflict with libprotobuf.so.18
/usr/bin/ld: warning: libprotobuf.so.9, needed by ../../../../lib/libORB_SLAM2.so, may conflict with libprotobuf.so.18
###

**Comment by AlejandroSilvestri** [comment] 2019-03-22 10:26
@Shashika007 

About protobuf lib conflict: it seems you have two versions installed.  You should use only the newest one (18 in your case).  -lprotobuf should link with the newest version, it seems your system is getting some old version (version 9) in the linking step.

This can explain the building errors.

Sorry I can't help you more with this specific error.

**Comment by AlejandroSilvestri** [comment] 2019-03-22 11:51
Well, can't access private members in System.h without modifying it, so I chose to comment private: specifier.  So I wrote it down to readme.md

I adopted the changes posted in this thread, so now osmap is more compatible with different installations.  So you may want to download the updated osmap version, and read again bundle instructions for orb-slam2.

I don't have any pending issue, I'll appreciate it if you want to sum up your status.  I know @Shashika007 has a conflict with protobuf versions in his system, I don't know @maxwu8416 status.

**Comment by AlejandroSilvestri** [comment] 2019-03-29 12:35
@maxwu8416 , @Shashika007 

Today I fixed Osmap.cpp and had a [confirmation that it's working fine](https://github.com/AlejandroSilvestri/osmap/issues/5#issuecomment-477831060), loading and saving maps.

I'm closing this issue, you are welcome to open a new one if you want to continue this conversation or let me know about your successful implementation.

**Closed as completed by AlejandroSilvestri** 2019-03-29 12:35 UTC
