### ISSUE TITLE
Chdir() is messing up path management after mapSave

### ISSUE THREAD

**Issue by mmajewsk** [AlejandroSilvestri/osmap#15] opened 2020-01-26 18:22 UTC
In this line: https://github.com/AlejandroSilvestri/osmap/blob/e7892640c128d3acaad3fcdaabf3d89b1233ddb9/src/Osmap.cpp#L79

The use of `chdir` is messing up paths, if you try to use them after mapSave

**Comment by AlejandroSilvestri** [comment] 2021-02-04 11:09
Duplicate of #14

@mmajewsk 

Thank you, I'm not fixing it, I believed the core value is the ability to create and load a map, and each implementation will vary the way it changes the directory.

**Closed as completed by AlejandroSilvestri** 2021-02-04 11:09 UTC
