### ISSUE TITLE
When I load the generated map, an error occurs in Rebuilds MapPoints obvervations ,because the size of the key frame's mvuRight is 0.

### ISSUE THREAD

**Issue by cugcsu** [AlejandroSilvestri/osmap#5] opened 2019-03-28 04:49 UTC
`// Rebuilds MapPoints obvervations
		size_t n = pKF->mvpMapPoints.size();
		for(size_t i=0; i<n; i++){
			MapPoint *pMP = pKF->mvpMapPoints[i];			
			if (pMP)
			{
				//if(pKF->mvuRight.size()>0)
					pMP->AddObservation(pKF, i);
			}
				
		}`
error occurs in AddObservation():
`void MapPoint::AddObservation(KeyFrame* pKF, size_t idx)
{
    unique_lock<mutex> lock(mMutexFeatures);
    if(mObservations.count(pKF))
        return;
    mObservations[pKF]=idx;

    if(pKF->mvuRight[idx]>=0)
        nObs+=2;
    else
        nObs++;
}`
because the size of the keyframe's attributes mvuRight's size is 0,pKF->mvuRight[idx] is wrong.

**Comment by AlejandroSilvestri** [comment] 2019-03-28 13:20
@cugcsu 

Thank you for your work.

This is the change needed, that I'll will add to the repository in a few days.  Add these 2 lines of code in [Osmap.cpp line 928](https://github.com/AlejandroSilvestri/osmap/blob/master/src/Osmap.cpp#L928):

    const_cast<std::vector<float>&>(pKF->mvuRight) = vector<float>(n,-1.0f);
    const_cast<std::vector<float>&>(pKF->mvDepth) = vector<float>(n,-1.0f);

They can be placed anywhere after the `int n` assignment in line 925 and before `for` in line 930.

Please let me know if it works for you, or if any new error shows up.

**Comment by cugcsu** [comment] 2019-03-29 01:31
@AlejandroSilvestri 
Yeah, I have added this code and can load the map properly. I will continue to run, thank you for your help.

**Comment by faresfaresCS** [comment] 2019-04-02 08:17
@cugcsu My program still crashes at rebuild() after I fixed Osmap.cpp file.
Any ideas or special instructions ? Can you share your code for loading the map ?
This is where I load my map:
```
/**
* This file is part of ORB-SLAM2.
*
* Copyright (C) 2014-2016 Raúl Mur-Artal <raulmur at unizar dot es> (University of Zaragoza)
* For more information see <https://github.com/raulmur/ORB_SLAM2>
*
* ORB-SLAM2 is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* ORB-SLAM2 is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with ORB-SLAM2. If not, see <http://www.gnu.org/licenses/>.
*/


#include<iostream>
#include<algorithm>
#include<fstream>
#include<chrono>

#include<ros/ros.h>
#include <cv_bridge/cv_bridge.h>

#include<opencv2/core/core.hpp>

#include "../../../include/System.h"
#include <geometry_msgs/PoseStamped.h>
#include "geometry_msgs/TransformStamped.h" 
#include <tf/tf.h> 
#include <tf/transform_datatypes.h> 
#include <tf/transform_broadcaster.h>
#include "../../../include/Converter.h"
#include "../../../include/Osmap.h"

using namespace std;
using namespace tf;

//#include <chrono>

class ImageGrabber
{
public:
    ImageGrabber(ORB_SLAM2::System* pSLAM):mpSLAM(pSLAM){}

    void GrabImage(const sensor_msgs::ImageConstPtr& msg);

    ORB_SLAM2::System* mpSLAM;
};

ORB_SLAM2::Osmap *osmap;

int main(int argc, char **argv)
{
    ros::init(argc, argv, "Mono");
    ros::start();

    if(argc != 3)
    {
        cerr << endl << "Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings" << endl;        
        ros::shutdown();
        return 1;
    }    

    // Create SLAM system. It initializes all system threads and gets ready to process frames.
    ORB_SLAM2::System SLAM(argv[1],argv[2],ORB_SLAM2::System::MONOCULAR,true);

    osmap = new ORB_SLAM2::Osmap(SLAM);
    osmap->mapLoad("myFirstMap.yaml");
    ImageGrabber igb(&SLAM);

    ros::NodeHandle nodeHandler;
    ros::Subscriber sub = nodeHandler.subscribe("/camera/image_raw", 1, &ImageGrabber::GrabImage,&igb);

    ros::spin();

    // Stop all threads
    SLAM.Shutdown();

    // Save camera trajectory
    SLAM.SaveKeyFrameTrajectoryTUM("KeyFrameTrajectory.txt");
    
    ros::shutdown();

    return 0;
}

void ImageGrabber::GrabImage(const sensor_msgs::ImageConstPtr& msg)
{
    // Copy the ros image message to cv::Mat.
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
        cv_ptr = cv_bridge::toCvShare(msg);
    }
    catch (cv_bridge::Exception& e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
        return;
    }

    cv::Mat pose = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());

    if (pose.empty())
        return;

    // transform into right handed camera frame
    tf::Matrix3x3 rh_cameraPose(  - pose.at<float>(0,0),   pose.at<float>(0,1),   pose.at<float>(0,2),
                                  - pose.at<float>(1,0),   pose.at<float>(1,1),   pose.at<float>(1,2),
                                    pose.at<float>(2,0), - pose.at<float>(2,1), - pose.at<float>(2,2));

    tf::Vector3 rh_cameraTranslation( pose.at<float>(0,3),pose.at<float>(1,3), - pose.at<float>(2,3) );

    //rotate 270deg about z and 270deg about x
    tf::Matrix3x3 rotation270degZX( 0, 0, 1,
                                   -1, 0, 0,
                                    0,-1, 0);

    //publish right handed, x forward, y right, z down (NED)
    static tf::TransformBroadcaster br;
    tf::Transform transformCoordSystem = tf::Transform(rotation270degZX,tf::Vector3(0.0, 0.0, 0.0));
    br.sendTransform(tf::StampedTransform(transformCoordSystem, ros::Time::now(), "camera_link", "camera_pose"));

    tf::Transform transformCamera = tf::Transform(rh_cameraPose,rh_cameraTranslation);
    br.sendTransform(tf::StampedTransform(transformCamera, ros::Time::now(), "camera_pose", "pose"));

    ofstream myfile;
    using namespace std::chrono;
    static milliseconds ms = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
    static std::string which_file = "1";
    if(duration_cast< milliseconds >(system_clock::now().time_since_epoch()) - ms > milliseconds(10))
    {
        which_file = which_file == "1" ? "2" : "1";
        ms = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
        myfile.open ("/home/fares/PycharmProjects/Point-Tracker/Data/realtimepos" + which_file + ".csv");
        myfile << pose.at<float>(0,3) << " " << pose.at<float>(1,3) << " " << pose.at<float>(2,3);
        myfile.close();
    }
}
```
Thanks

**Comment by AlejandroSilvestri** [comment] 2019-04-02 19:09
@faresfaresCS , 

It would help a lot if you can get the exact file and line of the error, so I can trace it.  Sadly I don't know how to tell cmake or the compiler to show that info when the error happens.

**Comment by faresfaresCS** [comment] 2019-04-02 19:14
Duplicate of #4 
Im working with ROS option. So Im calling save and laod from ros_mono.cc file which serves me as main as you can see.

Its crashing at "Osmap.cpp":
```
pKF->ComputeBoW();
```
&
```
pMP->UpdateNormalAndDepth()
```
ros_mono.cc:
```
/**
* This file is part of ORB-SLAM2.
*
* Copyright (C) 2014-2016 Raúl Mur-Artal <raulmur at unizar dot es> (University of Zaragoza)
* For more information see <https://github.com/raulmur/ORB_SLAM2>
*
* ORB-SLAM2 is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* ORB-SLAM2 is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with ORB-SLAM2. If not, see <http://www.gnu.org/licenses/>.
*/


#include<iostream>
#include<algorithm>
#include<fstream>
#include<chrono>

#include<ros/ros.h>
#include <cv_bridge/cv_bridge.h>

#include<opencv2/core/core.hpp>

#include "../../../include/System.h"
#include <geometry_msgs/PoseStamped.h>
#include "geometry_msgs/TransformStamped.h" 
#include <tf/tf.h> 
#include <tf/transform_datatypes.h> 
#include <tf/transform_broadcaster.h>
#include "../../../include/Converter.h"
#include "../../../include/Osmap.h"

using namespace std;
using namespace tf;

//#include <chrono>

class ImageGrabber
{
public:
    ImageGrabber(ORB_SLAM2::System* pSLAM):mpSLAM(pSLAM){}

    void GrabImage(const sensor_msgs::ImageConstPtr& msg);

    ORB_SLAM2::System* mpSLAM;
};

ORB_SLAM2::Osmap *osmap;

int main(int argc, char **argv)
{
    ros::init(argc, argv, "Mono");
    ros::start();

    if(argc != 3)
    {
        cerr << endl << "Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings" << endl;        
        ros::shutdown();
        return 1;
    }    

    // Create SLAM system. It initializes all system threads and gets ready to process frames.
    ORB_SLAM2::System SLAM(argv[1],argv[2],ORB_SLAM2::System::MONOCULAR,true);

    osmap = new ORB_SLAM2::Osmap(SLAM);

    osmap->mapLoad("myFirstMap.yaml");

    ImageGrabber igb(&SLAM);

    ros::NodeHandle nodeHandler;
    ros::Subscriber sub = nodeHandler.subscribe("/camera/image_raw", 1, &ImageGrabber::GrabImage,&igb);

    ros::spin();
    
    // Stop all threads
    SLAM.Shutdown();

    // Save camera trajectory
    SLAM.SaveKeyFrameTrajectoryTUM("KeyFrameTrajectory.txt");

    ros::shutdown();

    return 0;
}

void ImageGrabber::GrabImage(const sensor_msgs::ImageConstPtr& msg)
{
    // Copy the ros image message to cv::Mat.
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
        cv_ptr = cv_bridge::toCvShare(msg);
    }
    catch (cv_bridge::Exception& e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
        return;
    }

    cv::Mat pose = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());

    if (pose.empty())
        return;

    // transform into right handed camera frame
    tf::Matrix3x3 rh_cameraPose(  - pose.at<float>(0,0),   pose.at<float>(0,1),   pose.at<float>(0,2),
                                  - pose.at<float>(1,0),   pose.at<float>(1,1),   pose.at<float>(1,2),
                                    pose.at<float>(2,0), - pose.at<float>(2,1), - pose.at<float>(2,2));

    tf::Vector3 rh_cameraTranslation( pose.at<float>(0,3),pose.at<float>(1,3), - pose.at<float>(2,3) );

    //rotate 270deg about z and 270deg about x
    tf::Matrix3x3 rotation270degZX( 0, 0, 1,
                                   -1, 0, 0,
                                    0,-1, 0);

    //publish right handed, x forward, y right, z down (NED)
    static tf::TransformBroadcaster br;
    tf::Transform transformCoordSystem = tf::Transform(rotation270degZX,tf::Vector3(0.0, 0.0, 0.0));
    br.sendTransform(tf::StampedTransform(transformCoordSystem, ros::Time::now(), "camera_link", "camera_pose"));

    tf::Transform transformCamera = tf::Transform(rh_cameraPose,rh_cameraTranslation);
    br.sendTransform(tf::StampedTransform(transformCamera, ros::Time::now(), "camera_pose", "pose"));

    ofstream myfile;
    using namespace std::chrono;
    static milliseconds ms = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
    static std::string which_file = "1";
    if(duration_cast< milliseconds >(system_clock::now().time_since_epoch()) - ms > milliseconds(10))
    {
        which_file = which_file == "1" ? "2" : "1";
        ms = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
        myfile.open ("/home/fares/PycharmProjects/Point-Tracker/Data/realtimepos" + which_file + ".csv");
        myfile << pose.at<float>(0,3) << " " << pose.at<float>(1,3) << " " << pose.at<float>(2,3);
        myfile.close();
    }
}
```
Mono_Load is a file which I get when building the nodes for mono as mentioned in ROS Examples in https://github.com/raulmur/ORB_SLAM2.git

**Comment by AlejandroSilvestri** [comment] 2019-06-04 19:35
I just upload an Osmap viewer.  Check it out:

https://github.com/AlejandroSilvestri/Osmap-viewer

At least you can see the points cloud in your file.

**Comment by AlejandroSilvestri** [comment] 2019-06-09 19:28
I just upload an Osmap with verbose mode, generating data for debugging.

Please copy this data if crashing while loading and paste it here.

**Comment by AlejandroSilvestri** [comment] 2019-06-14 12:07
@faresfaresCS 

You can try opening the map with osmap viewer, so you can see if the map is actually there, or it is corrupted.

New verbose mode logs steps during rebuild, so we can track down what is causing the crash.   If you can activate verbose mode, please copy the console output here, so I can debug it.

**Closed as completed** 2019-06-18 11:37 UTC
